export const filmes = [
    {
        id: 1,
        titulo: "Star Wars: Episódio III - A Vingança dos Sith",
        diretor: "George Lucas",
        ano_lancamento: 2005,
        genero: "Ficção Científica",
        atores: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen"],
        sinopse: "Durante as Guerras Clônicas, Anakin Skywalker é seduzido pelo lado sombrio da Força e se transforma no temível Darth Vader. Ao mesmo tempo, a República Galáctica se transforma no Império Galáctico, levando à ascensão do Império e à queda dos Jedi.",
        classificacao: "PG-13",
    },
    {
        id: 2,
        titulo: "Vingadores: Ultimato",
        diretor: "Anthony Russo, Joe Russo",
        ano_lancamento: 2019,
        genero: "Ação",
        atores: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
        sinopse: "Os Vingadores se reúnem para desfazer as ações de Thanos e restaurar o equilíbrio no universo.",
        classificacao: "PG-13",
    },
    {
        id: 3,
        titulo: "Forrest Gump",
        diretor: "Robert Zemeckis",
        ano_lancamento: 1994,
        genero: "Drama",
        atores: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        sinopse: "A vida de Forrest Gump, um homem com QI abaixo da média, mas uma alma pura, testemunha e influencia várias eventos importantes na história dos Estados Unidos.",
        classificacao: "PG-13",
    },
    {
        id: 4,
        titulo: "Pulp Fiction",
        diretor: "Quentin Tarantino",
        ano_lancamento: 1994,
        genero: "Crime",
        atores: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
        sinopse: "Diferentes histórias entrelaçadas sobre crimes bizarros em Los Angeles.",
        classificacao: "R",
    },
    {
        id: 5,
        titulo: "Titanic",
        diretor: "James Cameron",
        ano_lancamento: 1997,
        genero: "Romance",
        atores: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
        sinopse: "O romance épico de Jack e Rose durante a viagem inaugural do Titanic, que termina em tragédia.",
        classificacao: "PG-13",
    },
    {
        id: 6,
        titulo: "Matrix",
        diretor: "Lana Wachowski, Lilly Wachowski",
        ano_lancamento: 1999,
        genero: "Ficção Científica",
        atores: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        sinopse: "Um hacker descobre a verdade sobre a realidade e sua participação em uma guerra contra máquinas inteligentes.",
        classificacao: "R",
    },
    {
        id: 7,
        titulo: "O Senhor dos Anéis: A Sociedade do Anel",
        diretor: "Peter Jackson",
        ano_lancamento: 2001,
        genero: "Fantasia",
        atores: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        sinopse: "Um hobbit é encarregado de destruir um poderoso anel para evitar que caia nas mãos do mal.",
        classificacao: "PG-13",
    },
    {
        id: 8,
        titulo: "O Rei Leão",
        diretor: "Roger Allers, Rob Minkoff",
        ano_lancamento: 1994,
        genero: "Animação",
        atores: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
        sinopse: "Um jovem leão príncipe foge de casa apenas para aprender a verdadeira significado de responsabilidade e valentia.",
        classificacao: "G",
    },
    {
        id: 9,
        titulo: "Interestelar",
        diretor: "Christopher Nolan",
        ano_lancamento: 2014,
        genero: "Ficção Científica",
        atores: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        sinopse: "Um grupo de exploradores viaja através de um buraco de minhoca espacial em busca de um novo lar para a humanidade.",
        classificacao: "PG-13",
    },
    {
        id: 10,
        titulo: "Pantera Negra",
        diretor: "Ryan Coogler",
        ano_lancamento: 2018,
        genero: "Ação",
        atores: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
        sinopse: "T'Challa, o rei recém-corado de Wakanda, deve defender seu país contra os inimigos internos e externos.",
        classificacao: "PG-13",
    },
    {
        id: 11,
        titulo: "Star Wars: Episódio IV - Uma Nova Esperança",
        diretor: "George Lucas",
        ano_lancamento: 1977,
        genero: "Ficção Científica",
        atores: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
        sinopse: "Um jovem fazendeiro chamado Luke Skywalker se junta a um grupo rebelde para combater o malvado Império Galáctico e resgatar a Princesa Leia.",
        classificacao: "PG",
    }
];

export default filmes;
